# Generated by Django 5.0 on 2023-12-31 00:27

import charities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='reg_number',
            field=models.CharField(max_length=10, validators=[charities.validators.RegNumberValidator()]),
        ),
    ]
